swagger: "2.0"
info:
  version: "1.0.0"
  title: Travel Plan API
host: localhost
basePath: /
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json

paths:

  /travel:
    x-swagger-pipe: getRestaurantsAndWeatherFromAddress
    get:
      description: Retrieve 10-day weather and restaurant list given an input address
      parameters:
        - name: address
          in: query
          description: address
          required: true
          type: string
      responses:
        default:
          description: Any
          schema:
            $ref: "#/definitions/Any"

definitions:
  Any:
    properties: {}
