swagger: "2.0"
info:
  version: "1.0.0"
  title: Usergrid Cloud Code Example
host: localhost
basePath: /
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json

paths:

  /orders:

    post:
      x-swagger-pipe: createOrder
      description: create an order in usergrid, send a push notification
      parameters:
        - name: body
          in: body
          description: body
          required: true
          schema:
            type: object
      responses:
        default:
          description: anything
          schema:
            $ref: "#/definitions/Any"

  /orders/{id}:

    parameters:
      - name: id
        in: path
        description: id
        required: true
        type: string

    get:
      x-swagger-pipe: getOrder
      description: get an order from usergrid, increment a counter
      responses:
        default:
          description: anything
          schema:
            $ref: "#/definitions/Any"

    delete:
      x-swagger-pipe: deleteOrder
      description: delete an order from usergrid, send an email notification
      responses:
        default:
          description: anything
          schema:
            $ref: "#/definitions/Any"

definitions:
  Any:
    properties: {}
